version: '3'
services:
  go_api:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4160"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
  postgres:
    image: postgres:10.6
    ports:
      - '3002:5432'
    environment:
      POSTGRES_USER: 'bond'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'bookstore'
  pgadmin:
    image: thajeztah/pgadmin4
    volumes:
      - ./pgadmin:/pgadmin
    ports:
      - '3004:5050'
    links:
      - postgres
  